networks:
  dev:

services:
  backend:
    container_name: auth_backend
    ports:
      - 8040:8040
    build:
      context: ./
    depends_on:
      - bd
    networks:
      - dev
  
  bd:
    container_name: auth_bd
    image: postgres:17.5-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    ports:
      - 5432:5432
    networks:
      - dev

